use crate::console::{CursorBlink, CursorStyle, FontKind};

pub struct Preset {
    pub name: &'static str,
    pub bg: u32,
    pub fg: u32,
    pub cursor: u32,
    pub cursor_style: CursorStyle,
    pub cursor_blink: CursorBlink,
    pub font: FontKind,
}

pub const PRESETS: &[Preset] = &[
    Preset{
        name: "default",
        bg: 0x000000,
        fg: 0xCCCCCC,
        cursor: 0xCCCCCC,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "amber monitor 1983",
        bg: 0x050200,
        fg: 0xFFB45E,
        cursor: 0xFF8C00,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "midnight hacker",
        bg: 0x000011,
        fg: 0xD0D0FF,
        cursor: 0xFFFFFF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::None,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "nordic ice",
        bg: 0x1E2330,
        fg: 0xD8DEE9,
        cursor: 0x88C0D0,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "classic dos steel",
        bg: 0x000000,
        fg: 0xC0C0C0,
        cursor: 0xFFFFFF,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "red alert",
        bg: 0x1A0000,
        fg: 0xFF6B6B,
        cursor: 0xFF0000,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "fog terminal",
        bg: 0x0F0F0F,
        fg: 0xA0A0A0,
        cursor: 0xC0C0C0,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "apple ii green",
        bg: 0x001400,
        fg: 0x7CFF7C,
        cursor: 0x33FF33,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "deep night terminal",
        bg: 0x070A14,
        fg: 0x9ADFEA,
        cursor: 0x57F2FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "rose quartz",
        bg: 0x131019,
        fg: 0xF7C9E6,
        cursor: 0xE98BC6,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "pink dusk tty",
        bg: 0x1A1118,
        fg: 0xE8A7C4,
        cursor: 0xD86A97,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "sepia desk terminal",
        bg: 0x2B2018,
        fg: 0xF5E8D7,
        cursor: 0xE3C7A0,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "arctic terminal",
        bg: 0x101622,
        fg: 0xE4ECF2,
        cursor: 0xA0D4FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::None,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "violet dusk crt",
        bg: 0x0A0612,
        fg: 0xD1BAFF,
        cursor: 0xB483FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "msx workshop",
        bg: 0x001428,
        fg: 0x7DD0FF,
        cursor: 0x449CFF,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "forest dusk workstation",
        bg: 0x0B100C,
        fg: 0xD6E8D0,
        cursor: 0x9CE0A9,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "plum synth",
        bg: 0x120416,
        fg: 0xE1B6FF,
        cursor: 0xC46DFF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "labcoat phosphor",
        bg: 0x0E0F14,
        fg: 0xE7E7EF,
        cursor: 0xCFCFEA,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "molten server rack",
        bg: 0x120A00,
        fg: 0xFFB97A,
        cursor: 0xFF7F24,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "coffee shop",
        bg: 0x1B0F08,
        fg: 0xECDCC6,
        cursor: 0xD5B89C,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "telemetry bay",
        bg: 0x0B1620,
        fg: 0xC7D6E8,
        cursor: 0x59E4FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "blueberry matrix",
        bg: 0x000A14,
        fg: 0x65C6FF,
        cursor: 0x00B8FF,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
];
