use crate::console::{CursorBlink, CursorStyle, FontKind};

pub struct Preset {
    pub name: &'static str,
    pub author: &'static str,
    pub description: &'static str,
    pub bg: u32,
    pub fg: u32,
    pub cursor: u32,
    pub cursor_style: CursorStyle,
    pub cursor_blink: CursorBlink,
    pub font: FontKind,
}

pub const PRESETS: &[Preset] = &[
    Preset {
        name: "default",
        author: "stratosdev",
        description: "Soft gray on black. Clean, classic, no-nonsense.",
        bg: 0x000000,
        fg: 0xCCCCCC,
        cursor: 0xCCCCCC,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "lemon",
        author: "anonymous",
        description: "Creamy pastel yellow terminal with warm graphite text. Soft, bright, and clean. Ideal for a modern light-mode console.",
        bg: 0xFFF9CC,
        fg: 0x3A3A3A,
        cursor: 0x705E00,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "stratos",
        author: "stratosdev",
        description: "A professional blue background and a nice blue tinted foreground. StratOS as intended (not really).",
        bg: 0x003366,
        fg: 0xDDEEFF,
        cursor: 0x66CCFF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "solarized dark",
        author: "ethanschoonover, stratosdev",
        description: "Ethan Schoonover's iconic Solarized palette. Calm contrast, harmonious hues.",
        bg: 0x002B36,
        fg: 0x93A1A1,
        cursor: 0x268BD2,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "amber monitor 1983",
        author: "stratosdev",
        description: "Vintage amber phosphor glow on deep coal.",
        bg: 0x050200,
        fg: 0xFFB45E,
        cursor: 0xFF8C00,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "midnight hacker",
        author: "stratosdev",
        description: "Shadow-blue backdrop with chilled pale blues.",
        bg: 0x000011,
        fg: 0xD0D0FF,
        cursor: 0xFFFFFF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::None,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "nordic ice",
        author: "stratosdev",
        description: "Frosted slate backdrop with pale icy accents.",
        bg: 0x1E2330,
        fg: 0xD8DEE9,
        cursor: 0x88C0D0,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "paper",
        author: "stratosdev",
        description: "Soft paper-white workspace with calm graphite text. Minimal, warm, notebook-like.",
        bg: 0xF2EFE6,
        fg: 0x3A3A3A,
        cursor: 0x6A6A6A,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "classic dos steel",
        author: "stratosdev",
        description: "Pure DOS black with cold steel gray type.",
        bg: 0x000000,
        fg: 0xC0C0C0,
        cursor: 0xFFFFFF,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "red alert",
        author: "stratosdev",
        description: "Dark blood-red base with alarm-light crimson text.",
        bg: 0x1A0000,
        fg: 0xFF6B6B,
        cursor: 0xFF0000,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "fog terminal",
        author: "stratosdev",
        description: "Muted charcoal haze with gentle smoky grays.",
        bg: 0x0F0F0F,
        fg: 0xA0A0A0,
        cursor: 0xC0C0C0,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "apple ii green",
        author: "stevejobs, stratosdev",
        description: "Retro green phosphor glow on forest black.",
        bg: 0x001400,
        fg: 0x7CFF7C,
        cursor: 0x33FF33,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "deep night terminal",
        author: "stratosdev",
        description: "Deep midnight navy with shimmering cyan traces.",
        bg: 0x070A14,
        fg: 0x9ADFEA,
        cursor: 0x57F2FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "rose quartz",
        author: "stratosdev",
        description: "Dusky purple stone with soft rose-pink glints.",
        bg: 0x131019,
        fg: 0xF7C9E6,
        cursor: 0xE98BC6,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "pink dusk tty",
        author: "stratosdev",
        description: "Wine-purple dusk washed in warm tabletop pink.",
        bg: 0x1A1118,
        fg: 0xE8A7C4,
        cursor: 0xD86A97,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "sepia desk terminal",
        author: "stratosdev",
        description: "Warm sepia parchment tones with creamy highlights.",
        bg: 0x2B2018,
        fg: 0xF5E8D7,
        cursor: 0xE3C7A0,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "arctic terminal",
        author: "stratosdev",
        description: "Polar night blue with glacial white accents.",
        bg: 0x101622,
        fg: 0xE4ECF2,
        cursor: 0xA0D4FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::None,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "violet dusk crt",
        author: "stratosdev",
        description: "Dark violet tube glow with soft lavender shine.",
        bg: 0x0A0612,
        fg: 0xD1BAFF,
        cursor: 0xB483FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
    Preset {
        name: "msx workshop",
        author: "stratosdev",
        description: "MSX blue console with icy cyan strokes.",
        bg: 0x001428,
        fg: 0x7DD0FF,
        cursor: 0x449CFF,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "forest dusk workstation",
        author: "stratosdev",
        description: "Dark evergreen shadow with mist-pale mint text.",
        bg: 0x0B100C,
        fg: 0xD6E8D0,
        cursor: 0x9CE0A9,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "plum synth",
        author: "stratosdev",
        description: "Deep 'synthwave' plum with neon-violet edges.",
        bg: 0x120416,
        fg: 0xE1B6FF,
        cursor: 0xC46DFF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "labcoat phosphor",
        author: "stratosdev",
        description: "Clinical charcoal panel lit by sterile white phosphor.",
        bg: 0x0E0F14,
        fg: 0xE7E7EF,
        cursor: 0xCFCFEA,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "molten server rack",
        author: "stratosdev",
        description: "Coal-black. Molten orange highlights.",
        bg: 0x120A00,
        fg: 0xFFB97A,
        cursor: 0xFF7F24,
        cursor_style: CursorStyle::Block,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Terminus8x16,
    },
    Preset {
        name: "coffee shop",
        author: "stratosdev",
        description: "Cozy espresso brown with smooth latte cream text.",
        bg: 0x1B0F08,
        fg: 0xECDCC6,
        cursor: 0xD5B89C,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "telemetry bay",
        author: "stratosdev",
        description: "Deep navy console with pastel telemetry blues.",
        bg: 0x0B1620,
        fg: 0xC7D6E8,
        cursor: 0x59E4FF,
        cursor_style: CursorStyle::Line,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Spleen8x16,
    },
    Preset {
        name: "blueberry matrix",
        author: "stratosdev",
        description: "Cold inky blue background with bright electric-blue text.",
        bg: 0x000A14,
        fg: 0x65C6FF,
        cursor: 0x00B8FF,
        cursor_style: CursorStyle::Underscore,
        cursor_blink: CursorBlink::Pulse,
        font: FontKind::Vga8,
    },
];
